export const MAX_POLYGON_VERTICES = 16;
export const POLYGON_VERTEX_COUNT_INDEX = 0;
export const POLYGON_VERTICES_INDEX = 1;
export const POLYGON_SIZE = POLYGON_VERTICES_INDEX + MAX_POLYGON_VERTICES * 2;
